### ISSUE TITLE
[Suggestion] TaskResultBuilder

### ISSUE THREAD

**Issue by piaste** [cmeeren/Cvdm.ErrorHandling#4]
Just throwing out an idea, it could be interesting to support the `task {}` CE from [TaskBuilder.fs](https://github.com/rspeele/TaskBuilder.fs), adding a `taskResult {}` CE and module which mirror `asyncResult {}`.

I'm unlikely to personally use such a feature, but it seems [there's some demand](https://github.com/rspeele/TaskBuilder.fs/issues/17).

**Comment by cmeeren** [comment]
I'm unlikely to use it too. In any case, since this will need a dependency on TaskBuilder.fs, I wouldn't be comfortable including it in this library. Anyone is of course free to take whatever they need from this library and adapt it to work with TaskBuilder.fs.

**Comment by cmeeren** [comment]
Just want to note that in v2.0.0, I have added overloads that can bind `Task<_>` and `Task` expressions (i.e., you don't have to manually call `Async.AwaitTask`). It's certainly not a `TaskResultBuilder` since the returned structure is still `Async<Result<_,_>>`, but it should make interop with `Task` code a bit better.

**Comment by cmeeren** [comment]
Implemented in FsToolkit.ErrorHandling 1.1.0: https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/18
