### ISSUE TITLE
AutoOpen from 0.4.0->0.5.0 is a binary (not source) breaking change

### ISSUE THREAD

**Issue by danyx23** [cmeeren/Cvdm.ErrorHandling#6]
Hi! Thanks for this really nice library! We just had a really weird problem around upgrading from 0.4.0 to 0.5.1 that others might run into as well so I wanted to document it here. 

Our setup was a Library that was using the Cvdm asyncResult and an executable that was referencing the library and also using Cvdm asyncResult itself. We use Paket to manage dependencies. After upgrading and recompiling, we all of a sudden had this error at runtime (compile worked fine):
```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$Registry>.$Edelweiss.Registry.Main' threw an exception. ---> System.MissingMethodException: Method not found: 'AsyncResultBuilder Cvdm.ErrorHandling.Helpers.get_asyncResult()'.
```

On the library, the version constraint for Cvdm.ErrorHandling was set to `~> 0` as our intent was that newer major versions should be fine.

I don't have the time right now to investigate exactly what was happening here, but after recompiling the library and the app with 0.5.1 the weird runtime error went away. I think there is nothing this library can do at this point, but maybe you can leave this ticket open for a little while so people running into this problem can find it?

**Comment by cmeeren** [comment]
Thanks for the report.

A couple of points:

* The library is still on 0.x.x, so any new version may be breaking. See the changelog for details.

* @piaste did the AutoOpen PR and took care to ensure that the change was not breaking. And if your problem went away after recompiling (which is always a good idea whenever there's strange problems like these - or indeed after any nuget package changes), then as far as I can see, this isn't really a problem - just some stale binaries or metadata or what have you in your build output.

**Comment by piaste** [comment]
To clarify, I had added several tests to ensure that the automatic open wouldn't break existing *code* (because it would have been quite counter-intuitive to have to _remove_ `open` statements to make code compile).

I did not actually test the behaviour of a binary compiled against 0.4.0 using explicit `open` statements, because I believed that the `[<AutoOpen>]` attribute was merely compile-time sugar. I'm surprised to learn that it's not the case, but it's good to know about this quirk. Thanks for the report!
